services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - proxy

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: cora_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - proxy

volumes:
  db_data:

networks:
  proxy:
    external: true
