# Generated by Django 5.2 on 2025-05-09 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferencia', '0008_conferencia_archivo_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='conferencia.conferencia')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.pregunta')),
            ],
        ),
    ]
