# Generated by Django 5.2.1 on 2025-05-23 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0013_delete_evaluacion'),
        ('formulario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retroalimentacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='conferencia.conferencia')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('conferencia', 'revisor')},
            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='evaluacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formulario.evaluacion'),
            preserve_default=False,
        ),
    ]
