# Generated by Django 5.2.1 on 2025-05-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0013_delete_evaluacion'),
        ('formulario', '0002_evaluacion_respuesta_evaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencia.conferencia'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='retroalimentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.evaluacion'),
        ),
    ]
