# Generated by Django 5.2.1 on 2025-05-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_remove_evaluacion_fecha_alter_evaluacion_conferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.evaluacion'),
        ),
    ]
