# Generated by Django 5.2.1 on 2025-05-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_respuesta_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='formulario.evaluacion'),
            preserve_default=False,
        ),
    ]
