# Generated by Django 5.2 on 2025-05-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('meses', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('horas', models.IntegerField(default=0)),
                ('minutos', models.IntegerField(default=0)),
            ],
        ),
    ]
