# Generated by Django 5.2 on 2025-05-08 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0003_invitacionrevisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionrevisor',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitacionrevisor',
            name='conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferencia.conferencia'),
        ),
    ]
