# Generated by Django 5.2 on 2025-05-09 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0004_invitacionrevisor_fecha_envio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferencia',
            name='formulario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_organizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
