# Generated by Django 5.2 on 2025-05-09 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0005_conferencia_autor_conferencia_formulario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='conferencia',
            name='formulario',
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
