# Generated by Django 5.2 on 2025-05-09 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0006_remove_conferencia_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_autorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_organizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
