# Generated by Django 5.2 on 2025-05-09 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0007_conferencia_autor_alter_conferencia_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='archivo_zip',
            field=models.FileField(blank=True, null=True, upload_to='conferencias_zips/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
