# Generated by Django 5.2 on 2025-05-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0008_conferencia_archivo_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacionrevisor',
            name='conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_revisor', to='conferencia.conferencia'),
        ),
    ]
