# Generated by Django 5.2.1 on 2025-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0010_alter_invitacionrevisor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacionrevisor',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
