# Generated by Django 5.2.1 on 2025-05-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0012_evaluacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
