# Generated by Django 5.2.1 on 2025-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0013_delete_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='estado_revision',
            field=models.CharField(blank=True, choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], max_length=20, null=True),
        ),
    ]
