# Generated by Django 5.2.1 on 2025-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0014_conferencia_estado_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='trabajo_reportado',
            field=models.BooleanField(default=False),
        ),
    ]
