# Generated by Django 5.2.1 on 2025-05-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0015_conferencia_trabajo_reportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='categoria',
            field=models.CharField(choices=[('Ingenieria', 'Ingeniería'), ('Medicina', 'Medicina'), ('Letras', 'Letras'), ('Contabilidad', 'Contabilidad')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
